version: "3"

services:
  api:
    build: .
    container_name : AIO-FastAPI-Linux
    environment:
      - TZ=Asia/Singapore
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - 84:84
    volumes:
      - ./api:/api